#docker-machine ssh
#sudo sysctl -w vm.max_map_count=262144
#exit

version: '3'
services:
  elasticsearch:
    environment:
      - cluster.name=elasticsearch
      - network.publish_host=elasticsearch
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    environment:
      - ELASTICSEARCH_HOSTS="http://elasticsearch:9200/"
      - SERVER_BASE_PATH="/kibana"
    image: docker.elastic.co/kibana/kibana:6.7.1
    expose:
      - 5601
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch


  fuzzer:
    image: fuzz:latest
    expose:
      - 8890
    ports:
      - 8890:8890
    command: python app.py -o http://elasticsearch:9200 -i logs_index
    depends_on:
      - elasticsearch

